### ISSUE TITLE
Add environment variables to build pod

### ISSUE THREAD

**Issue by pnispero** [eed-web-application/core-build-system#16]
### ADBS_OS_ENVIRONMENT
Would like to add an additional env variable `ADBS_OS_ENVIRONMENT` to pass to the build pod. 
For example, if building a component for multiple OS, each build pod would get their `ADBS_OS_ENVIRONMENT` filled in appropriately. like RHEL8, ROCKY9, etc.
### ADBS_BUILD_TYPE
Would like to add an additional env variable `ADBS_BUILD_TYPE` to pass to the build pod. 
For example, if user is doing a remote build, they can specify "normal" or "container" build.
This `ADBS_BUILD_TYPE` would be passed in from the CLI to the backend to the build pod.

For context, "normal" and "container" build are mostly the same, the only difference is that the "container" will additionally build an image with all dependencies needed for an app to run, and push to registry.

**Comment by bisegni** [comment]
ok perfect
